# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-planton" do
  name "project-planton"
  desc "Project Planton CLI - Infrastructure as Code made simple"
  homepage "https://github.com/project-planton/project-planton"
  version "0.2.271"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-planton"

  on_macos do
    on_intel do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_darwin_amd64.tar.gz"
      sha256 "e444f85fc28687c8f8085164c811ee01d4b99cb6dba264b1085c353f9add770d"
    end
    on_arm do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_darwin_arm64.tar.gz"
      sha256 "277d1678870a1385ab4e629fe2d32db85678373f3dc061cfc762754cc3a2a972"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_linux_amd64.tar.gz"
      sha256 "2cc08763305461e3b48be48bb92d386fc0daa21ddc653e93e2b99aaef3ea50d0"
    end
    on_arm do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_linux_arm64.tar.gz"
      sha256 "95cc34659925e66aa7fe6228db11b44c0c89868aef95e76e91f68be669311837"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/project-planton"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "Project Planton CLI helps you manage infrastructure deployments."
    ""
    "Quick Start"
    ""
    "1. Initialize a new project:"
    "   project-planton init"
    ""
    "2. Check the version:"
    "   project-planton version"
    ""
    "3. Get help:"
    "   project-planton --help"
    ""
    "Documentation: https://github.com/project-planton/project-planton"
  end

  # No zap stanza required
end
