# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-planton" do
  name "project-planton"
  desc "Project Planton CLI - Infrastructure as Code made simple"
  homepage "https://github.com/project-planton/project-planton"
  version "0.2.276"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-planton"

  on_macos do
    on_intel do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_darwin_amd64.tar.gz"
      sha256 "dad211742c4ce7199b4a2bf4864e8c1fe1129236e89dd4ed57143c664246a415"
    end
    on_arm do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_darwin_arm64.tar.gz"
      sha256 "2f641614c6898bed65348be7022b90c799bfd7b4e6ba87372ddf9f225bc0642e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_linux_amd64.tar.gz"
      sha256 "f45fe4264f8336cc6ab5b8b68a1747ae1708e34c7208adc5d6d1c00c7b858332"
    end
    on_arm do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_linux_arm64.tar.gz"
      sha256 "2f3c79e31d61fbce57ad7e7daccccdd1d1a44bac2ac636ec531e9fff7b5bd56c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/project-planton"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "Project Planton CLI helps you manage infrastructure deployments."
    ""
    "Quick Start"
    ""
    "1. Initialize a new project:"
    "   project-planton init"
    ""
    "2. Check the version:"
    "   project-planton version"
    ""
    "3. Get help:"
    "   project-planton --help"
    ""
    "Documentation: https://github.com/project-planton/project-planton"
  end

  # No zap stanza required
end
