# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-planton" do
  name "project-planton"
  desc "Project Planton CLI - Infrastructure as Code made simple"
  homepage "https://github.com/project-planton/project-planton"
  version "0.2.275"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-planton"

  on_macos do
    on_intel do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_darwin_amd64.tar.gz"
      sha256 "4cba919559b8b318a54d97614cbdd737f665dc233eb9503d3484667475f6ebc0"
    end
    on_arm do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_darwin_arm64.tar.gz"
      sha256 "4e9faa382b518215a22e1511e309e5759fa4246a88506a33cc9344e5cb6410fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_linux_amd64.tar.gz"
      sha256 "05e04ab461b16f56f3c671b7e3404985b3fbd14049e82bb1bedc5604af3fa0e1"
    end
    on_arm do
      url "https://github.com/project-planton/project-planton/releases/download/v#{version}/project-planton_#{version}_linux_arm64.tar.gz"
      sha256 "f53f639471da34b35dc26d61c902cd469cb9b099796ee5ed846c7da349e5aa33"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/project-planton"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "Project Planton CLI helps you manage infrastructure deployments."
    ""
    "Quick Start"
    ""
    "1. Initialize a new project:"
    "   project-planton init"
    ""
    "2. Check the version:"
    "   project-planton version"
    ""
    "3. Get help:"
    "   project-planton --help"
    ""
    "Documentation: https://github.com/project-planton/project-planton"
  end

  # No zap stanza required
end
